Use checkbox for 'Inc. in Backup' column
QubesOS/qubes-manager pull request #275
Opened 2020-11-14 16:30 UTC by donob4n

It was really simple thanks to model/view architecture.

I tried to center the checkbox on the column but it will require to subclass ItemDelegate or similar. Maybe it would be just fine with a short column header text (e.g. "Inc. in Backup") or using two lines instead one.

2020-12-10 04:35 UTC, marmarek commented
> "Inc. in Backup"

Maybe just "Backup"? Possibly with a tooltip "Include in Backup"?

2020-12-10 04:37 UTC, marmarek requested changes

2020-12-10 04:37 UTC, marmarek commented on qubesmanager/qube_manager.py
> +                vm.vm.include_in_backups = (value == 2)
What is value `2`? Isn't there some nice constant like `Qt.Checked`?

2020-12-12 13:17 UTC, donob4n commented
> > "Inc. in Backup"
> 
> Maybe just "Backup"? Possibly with a tooltip "Include in Backup"?

With just 'Backup' looks nice. I'm not sure about what to do with the tooltip. No other headers or cells have tooltips so it can be hard to found. In case you prefer to add it, where do you see more useful in the column header or in all 'Backup' cells?

2020-12-15 14:54 UTC, marmarek commented
PipelineRetry

2020-12-16 00:36 UTC, marmarek commented
PipelineRetry

2020-12-16 00:36 UTC, marmarek approved these changes

2021-01-05 20:53 UTC, merged