global_settings: better handling of exc in GuiVM
QubesOS/qubes-manager pull request #295
Opened 2021-06-22 10:23 UTC by fepitre

2021-06-23 10:56 UTC, fepitre commented
PipelineRetry

2021-06-27 10:33 UTC, fepitre commented
PipelineRetry

2021-06-30 16:30 UTC, marmarek requested changes

2021-06-30 16:30 UTC, marmarek commented on qubesmanager/global_settings.py
> +        raise exc.QubesException(msg + '(%s)', p.stderr.decode('utf-8'))
```suggestion
        raise exc.QubesException(msg + ' (%s)', p.stderr.decode('utf-8'))
```

2021-06-30 16:30 UTC, marmarek commented on qubesmanager/global_settings.py
> +        raise exc.QubesException(msg + '(%s)', p.returncode)
```suggestion
        raise exc.QubesException(msg + ' (%s)', p.returncode)
```

2021-06-30 21:25 UTC, marmarek approved these changes

2021-06-30 22:27 UTC, merged