Fix VM sorting order in Qube Manager if Sorting by State
QubesOS/qubes-manager pull request #324
Opened 2022-09-28 14:28 UTC by marmarta

Previously the sorting order depended on alphabetically sorting the dictionary containing state, which was less than ideal. Now it will use a reasonable order (from more to less running, and within a given state, no updates come before updates-available)

fixes QubesOS/qubes-issues#7073

2022-11-29 19:35 UTC, marmarek requested changes

2022-11-29 19:35 UTC, marmarek commented on qubesmanager/qube_manager.py
> +                        "purple", "black"].index(vmcolor))
`vm.label` is a `Label` object, which has `index` property. Better use that.

2022-12-05 12:47 UTC, marmarta commented
fixed

2022-12-05 13:45 UTC, marmarek approved these changes

2022-12-05 13:45 UTC, merged