Add explanation why you can't use vm settings with AdminVMs
QubesOS/qubes-manager pull request #328
Opened 2022-11-21 11:20 UTC by marmarta

fixes QubesOS/qubes-issues#7897

2022-11-29 20:54 UTC, marmarek requested changes

2022-11-29 20:54 UTC, marmarek commented on qubesmanager/settings.py
> +        return 1
For this to take effect, `main()` call below needs to use the return value, like `sys.exit(main())`

2022-12-05 12:42 UTC, marmarta commented
fixed

2022-12-05 13:24 UTC, marmarek approved these changes

2022-12-05 13:45 UTC, merged