Check if default_netvm is running when changing netvm
QubesOS/qubes-manager pull request #346
Opened 2023-05-12 14:30 UTC by marmarta

Changing netvm checks if new netvm is running, and if not asks to start it - this didn't happen for default netvm. Now it will.

fixes QubesOS/qubes-issues#8156

2023-05-13 10:37 UTC, marmarek requested changes

2023-05-13 10:37 UTC, marmarek commented on qubesmanager/settings.py
> +                    print("netvm", type(netvm))
leftover debug print

2023-05-13 12:46 UTC, marmarta commented on qubesmanager/settings.py
> +                    print("netvm", type(netvm))
done

2023-05-24 02:39 UTC, marmarek approved these changes

2023-05-24 02:39 UTC, merged