Improve field order in new fw window
QubesOS/qubes-manager pull request #351
Opened 2023-06-28 16:12 UTC by marmarta

fixes QubesOS/qubes-issues#8236

2023-07-01 14:29 UTC, marmarek requested changes

2023-07-01 14:29 UTC, marmarek commented on ui/newfwruledlg.ui
> -  <tabstop>serviceComboBox</tabstop>
I don't think it should be dropped from here.

2023-07-12 19:34 UTC, marmarek requested changes
Something is still wrong with the focus. Previously, when dialog was opened, it started with focus on the address field (expected behavior), now it starts with focus on cancel (or simply nothing, and cancel happen to be default button?).

2023-07-17 11:23 UTC, marmarta commented
I hate tab order. Anyway, closing this and pushing a better one.

2023-07-17 11:23 UTC, closed without merging