Set menu-items feature instead of running qvm-appmenus
QubesOS/qubes-manager pull request #359
Opened 2023-09-18 20:42 UTC by marmarta

Make it so that vm settings set menu-items feature instead of running qvm-appmenus

references QubesOS/qubes-issues#8494

2023-09-19 08:55 UTC, Rudd-O approved these changes

2023-09-19 18:29 UTC, marmarek requested changes

2023-09-19 18:29 UTC, marmarek commented on qubesmanager/appmenu_select.py
> +            self.vm.features.set('menu-items', " ".join(new_whitelisted))
`Features object has no attribute "set"`
It's a dict.

2023-10-06 01:43 UTC, marmarek approved these changes

2023-10-08 01:05 UTC, marmarek approved these changes

2023-10-08 01:50 UTC, merged