Improved tests and assorted fixes
QubesOS/qubes-manager pull request #400
Opened 2024-12-10 16:13 UTC by marmarta

- tests now can be run in VM, use mock Admin API and not blasphemy and vileness of hacking an existing qubes install (also they take roughly 1/10 of the time)
- do not re-save firewall if firewall was not changed
- make firewall edit dialog properly asynchroneous
- fix superfluous feature changes in vm settings
- fix netvm warnings in vm settings
- fix random weird package references in vm settings (as in firewall.datetime)
- fix two qubes() objects being used in vm settings

2024-12-10 16:32 UTC, marmarta commented
This requires https://github.com/QubesOS/qubes-core-admin-client/pull/323 (also so that the tests run at all).

2024-12-14 17:08 UTC, marmarek commented
PipelineRetry

2024-12-14 17:09 UTC, marmarek commented
Deb package fails to build:
```
18:54:11 [qb] >>> dh_install: warning: qubes-manager missing files: /usr/lib/*/dist-packages/qubesmanager/tests/test_create_new_vm.py
```

2024-12-15 00:35 UTC, marmarek requested changes
Great work!
There are few minor remarks. Plus it explode spectacularly (`Fatal Python error: Aborted`) on the first test...

2024-12-17 15:48 UTC, marmarta commented on qubesmanager/tests/test_qube_manager.py
> +# The Qubes OS Project, http://www.qubes-os.org
10/10 for sarcasm

2024-12-17 16:11 UTC, marmarta commented on qubesmanager/tests/test_qube_manager.py
> +# it under the terms of the GNU Lesser General Public License as published by
As files in this repo have inconsistent licensing (e.g. https://github.com/QubesOS/qubes-manager/blob/main/qubesmanager/appmenu_select.py where both GPL and LGPL are mentioned ), which one should I use?

2024-12-17 16:28 UTC, marmarta commented on qubesmanager/tests/test_qube_manager.py
> +    _select_vm(qubes_manager, 'fedora-35')
Do you think it makes sense to update mockups with new template names when it doesn't actually influence functionality?

2024-12-17 16:28 UTC, marmarta commented on qubesmanager/tests/test_clone_vm.py
> +TEST_VMS = ["test-blue", "test-red", ""]
will add explanatory comment

2024-12-17 17:06 UTC, marmarek commented on qubesmanager/tests/test_qube_manager.py
> +    _select_vm(qubes_manager, 'fedora-35')
When it doesn't, not really. But there may be cases where it does - like the EOL check (it does have a fallback list mapping specific names to dates). And while the EOL check specifically is in another repository, there may be other places that would benefit from some specific names. And the way it's done now, updating template names in mockups require also changing all its users...

2024-12-17 17:45 UTC, marmarek commented on qubesmanager/tests/test_qube_manager.py
> +# it under the terms of the GNU Lesser General Public License as published by
Should be GPL in this repo

2024-12-19 17:56 UTC, marmarek commented
Debian package fails to build

2025-01-03 04:04 UTC, marmarek requested changes

2025-01-03 04:04 UTC, marmarek commented on codecov.yml
> +ignore:
I would prefer an `--omit=` option in run-tests.sh script, so it isn't tied to specific service processing the coverage data, and will work when inspecting the data locally too.

2025-01-03 16:12 UTC, marmarta commented
PipelineRetryFailed

2025-01-03 17:20 UTC, marmarek approved these changes

2025-01-03 17:37 UTC, merged